apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: groovy
  labels:
    app.kubernetes.io/version: "0.2"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/displayName: Groovy
    tekton.dev/categories: Build Tools
    tekton.dev/tags: build-tool
    tekton.dev/platforms: "linux/amd64,linux/s390x,linux/ppc64le"
    artifacthub.io/provider: "hurzelpurzel"
    artifacthub.io/license: "Apache-2.0"
    artifacthub.io/alternativeName: "groovy"
spec:
  description: >-
    This Task can be used to run a Groovy script.
  workspaces:
    - name: source
      description: The workspace consisting of the  project.
  params:
    - name: GROOVY_IMAGE
      description: Groovy base image.
      type: string
      default: docker.io/library/groovy:latest
    - name: PROJECT_DIR
      description: The directory containing groovy scripts
      type: string
      default: "."
    - name: SCRIPT
      description: 'The groovy script to run (default: main.groovy)'
      type: string
      default: "main.groovy"
  steps:
    - name: groovy-task
      image: $(params.GROOVY_IMAGE)
      workingDir: $(workspaces.source.path)/$(params.PROJECT_DIR)
      command: ["groovy"]
      args:
        - "$(params.SCRIPT)"
      env:
        - name: WORKSPACE_SOURCE
          value: $(workspaces.source.path)